
# ruff: noqa: E501
# Imports
import json

from beet import Context
from stewbeet import create_gradient_text, write_function


# Setup the interactive configuration display function
def setup_config_display(ctx: Context) -> None:
	ns: str = ctx.project_id

	LIFE_STEAL_TEXT: str = json.dumps(create_gradient_text(f"[Life Steal Configuration v{ctx.project_version}]", "#FF0000", "#FF7300"))
	NUMERIC_SETTING: str = json.dumps(create_gradient_text("Numeric Settings:", "#68D4D4", "#009696"))
	BOOLEAN_SETTING: str = json.dumps(create_gradient_text("Toggle Settings (1 = enabled, 0 = disabled):", "#68D4D4", "#009696"))

	write_function(f"{ns}:_config", f"""
# Display configuration header
tellraw @s {LIFE_STEAL_TEXT}

# Display important warning about server setup
tellraw @s [{{"text":"⚠ IMPORTANT: ","color":"gold"}},{{"text":"For banning to work on servers, set ","color":"yellow"}},{{"text":"function-permission-level=3","color":"red"}},{{"text":" in server.properties!","color":"yellow"}}]

# Numeric settings
tellraw @s ["\\n",{NUMERIC_SETTING}]
tellraw @s [{{"text":"- Max Hearts: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set MAX_HEARTS {ns}.data 20"}},"hover_event":{{"action":"show_text","value":{{"text":"Enter the maximum number of hearts a player can have (absolute maximum)\\nDefault: 20","color":"white"}}}}}},{{"score":{{"name":"MAX_HEARTS","objective":"{ns}.data"}},"color":"yellow"}},{{"text":" 👈","color":"gray"}}]
tellraw @s [{{"text":"- Max Hearts By Consuming: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set MAX_HEARTS_BY_CONSUMING {ns}.data 20"}},"hover_event":{{"action":"show_text","value":{{"text":"Enter the maximum hearts obtainable by consuming crafted hearts\\nAdditional hearts can only be gained through kills\\nDefault: 20","color":"white"}}}}}},{{"score":{{"name":"MAX_HEARTS_BY_CONSUMING","objective":"{ns}.data"}},"color":"yellow"}},{{"text":" 👈","color":"gray"}}]
tellraw @s [{{"text":"- Min Hearts: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set MIN_HEARTS {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Enter the minimum number of hearts a player can have\\nDefault: 1","color":"white"}}}}}},{{"score":{{"name":"MIN_HEARTS","objective":"{ns}.data"}},"color":"yellow"}},{{"text":" 👈","color":"gray"}}]
tellraw @s [{{"text":"- Revived Hearts: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set REVIVED_HEARTS {ns}.data 4"}},"hover_event":{{"action":"show_text","value":{{"text":"Enter the number of hearts a player respawns with when revived\\nDefault: 4","color":"white"}}}}}},{{"score":{{"name":"REVIVED_HEARTS","objective":"{ns}.data"}},"color":"yellow"}},{{"text":" 👈","color":"gray"}}]

# Boolean settings
tellraw @s ["\\n",{BOOLEAN_SETTING}]
execute if score NATURAL_DEATH_HEART_LOSE {ns}.data matches 1 run tellraw @s [{{"text":"- Natural Death Heart Lose: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set NATURAL_DEATH_HEART_LOSE {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to disable - Players won't lose hearts when dying to non-player causes\\nDefault: Enabled","color":"white"}}}}}},{{"text":"Enabled","color":"green"}},{{"text":" 👈","color":"gray"}}]
execute if score NATURAL_DEATH_HEART_LOSE {ns}.data matches 0 run tellraw @s [{{"text":"- Natural Death Heart Lose: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set NATURAL_DEATH_HEART_LOSE {ns}.data 1"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to enable - Players will lose hearts when dying to non-player causes\\nDefault: Enabled","color":"white"}}}}}},{{"text":"Disabled","color":"red"}},{{"text":" 👈","color":"gray"}}]
execute if score NATURAL_DEATH_HEART_DROP {ns}.data matches 1 run tellraw @s [{{"text":"- Natural Death Heart Drop: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set NATURAL_DEATH_HEART_DROP {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to disable - Hearts won't drop at death location when dying to non-player causes\\nDefault: Enabled","color":"white"}}}}}},{{"text":"Enabled","color":"green"}},{{"text":" 👈","color":"gray"}}]
execute if score NATURAL_DEATH_HEART_DROP {ns}.data matches 0 run tellraw @s [{{"text":"- Natural Death Heart Drop: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set NATURAL_DEATH_HEART_DROP {ns}.data 1"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to enable - Hearts will drop at death location when dying to non-player causes\\nDefault: Enabled","color":"white"}}}}}},{{"text":"Disabled","color":"red"}},{{"text":" 👈","color":"gray"}}]
execute if score USE_HALF_HEARTS {ns}.data matches 1 run tellraw @s [{{"text":"- Half Hearts Mode: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set USE_HALF_HEARTS {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to disable - Hearts will be tracked in whole numbers\\nWarning: This will convert all players' hearts!\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Enabled","color":"green"}},{{"text":" 👈","color":"gray"}}]
execute if score USE_HALF_HEARTS {ns}.data matches 0 run tellraw @s [{{"text":"- Half Hearts Mode: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set USE_HALF_HEARTS {ns}.data 1"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to enable - Hearts will be tracked in 0.5 increments\\nWarning: This will convert all players' hearts!\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Disabled","color":"red"}},{{"text":" 👈","color":"gray"}}]
execute if score BAN_REACHING_MIN_HEARTS {ns}.data matches 1 run tellraw @s [{{"text":"- Ban Reaching Min Hearts: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set BAN_REACHING_MIN_HEARTS {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to disable - Players won't be banned when reaching minimum hearts\\nDefault: Enabled","color":"white"}}}}}},{{"text":"Enabled","color":"green"}},{{"text":" 👈","color":"gray"}}]
execute if score BAN_REACHING_MIN_HEARTS {ns}.data matches 0 run tellraw @s [{{"text":"- Ban Reaching Min Hearts: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set BAN_REACHING_MIN_HEARTS {ns}.data 1"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to enable - Players will be banned when reaching minimum hearts\\nDefault: Enabled","color":"white"}}}}}},{{"text":"Disabled","color":"red"}},{{"text":" 👈","color":"gray"}}]
execute if score SPECTATOR_INSTEAD {ns}.data matches 1 run tellraw @s [{{"text":"- Spectator Instead of Ban: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set SPECTATOR_INSTEAD {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to disable - Players will be banned (if BAN_REACHING_MIN_HEARTS is enabled)\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Enabled","color":"green"}},{{"text":" 👈","color":"gray"}}]
execute if score SPECTATOR_INSTEAD {ns}.data matches 0 run tellraw @s [{{"text":"- Spectator Instead of Ban: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set SPECTATOR_INSTEAD {ns}.data 1"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to enable - Players will be moved to spectator mode instead of being banned\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Disabled","color":"red"}},{{"text":" 👈","color":"gray"}}]
execute if score LAST_CHANCE {ns}.data matches 1 run tellraw @s [{{"text":"- Last Chance (Half Heart): ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set LAST_CHANCE {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to disable - Players will lose a full heart normally\\nOnly works when half hearts mode is disabled\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Enabled","color":"green"}},{{"text":" 👈","color":"gray"}}]
execute if score LAST_CHANCE {ns}.data matches 0 run tellraw @s [{{"text":"- Last Chance (Half Heart): ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set LAST_CHANCE {ns}.data 1"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to enable - When dying at MIN+1 hearts, player survives with MIN+0.5 hearts\\nOnly works when half hearts mode is disabled\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Disabled","color":"red"}},{{"text":" 👈","color":"gray"}}]
execute if score STEAL_ON_KILL {ns}.data matches 1 run tellraw @s [{{"text":"- Steal On Kill: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set STEAL_ON_KILL {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to disable - Killing players won't reward hearts or remove them from victims\\nDefault: Enabled","color":"white"}}}}}},{{"text":"Enabled","color":"green"}},{{"text":" 👈","color":"gray"}}]
execute if score STEAL_ON_KILL {ns}.data matches 0 run tellraw @s [{{"text":"- Steal On Kill: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set STEAL_ON_KILL {ns}.data 1"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to enable - Killing players will reward hearts and remove them from victims\\nDefault: Enabled","color":"white"}}}}}},{{"text":"Disabled","color":"red"}},{{"text":" 👈","color":"gray"}}]
execute if score INSTANTLY_CONSUME_HEARTS {ns}.data matches 1 run tellraw @s [{{"text":"- Instantly Consume Hearts: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set INSTANTLY_CONSUME_HEARTS {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to disable - Hearts will need to be fully consumed (eating animation)\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Enabled","color":"green"}},{{"text":" 👈","color":"gray"}}]
execute if score INSTANTLY_CONSUME_HEARTS {ns}.data matches 0 run tellraw @s [{{"text":"- Instantly Consume Hearts: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set INSTANTLY_CONSUME_HEARTS {ns}.data 1"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to enable - Hearts will be consumed instantly when used\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Disabled","color":"red"}},{{"text":" 👈","color":"gray"}}]
execute if score NO_HEART_DROP_OR_STEAL {ns}.data matches 1 run tellraw @s [{{"text":"- No Heart Drop: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set NO_HEART_DROP_OR_STEAL {ns}.data 0"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to disable - Hearts will drop/be stolen normally on death\\nOverrides STEAL_ON_KILL by preventing all heart steal/drop on death\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Enabled","color":"green"}},{{"text":" 👈","color":"gray"}}]
execute if score NO_HEART_DROP_OR_STEAL {ns}.data matches 0 run tellraw @s [{{"text":"- No Heart Drop: ","color":"aqua","click_event":{{"action":"suggest_command","command":"/scoreboard players set NO_HEART_DROP_OR_STEAL {ns}.data 1"}},"hover_event":{{"action":"show_text","value":{{"text":"Click to enable - Hearts won't drop or be stolen when players die\\nOverrides STEAL_ON_KILL by preventing all heart steal/drop on death\\nDefault: Disabled","color":"white"}}}}}},{{"text":"Disabled","color":"red"}},{{"text":" 👈","color":"gray"}}]
""")

